[spectrum]

[spectrum.regions]

[spectrum.regions.full]
limits = {"min" = 200, "max" = 3600}

[spectrum.regions.full_first_and_second]
limits = {"min" = 800, "max" = 3500}

[spectrum.regions.low]
limits = {"min" = 150, "max" = 850, "extra_margin" = 10}

[spectrum.regions.mid]
limits = {"min" = 1850, "max" = 2150, "extra_margin" = 10}
